sudo: false
dist: trusty
language: python
cache: pip
python:
    - 2.7.13
    - 3.6
install:
    - pip install --upgrade pip setuptools
    - pip install flake8
before_script:
    - flake8 . --count --exclude=./howmanypeoplearearound/plotlyjs.py --exit-zero --max-line-length=127 --statistics  # 127 == GitHub editor width
    - flake8 . --select=E999,F821,F822,F823 --statistics  # Stop build on syntax errors
script: python -V  # a basic no-op
